#segndo desafío, de pdf
#lunes/07/2024


#10) Cree un programa en el cual pida al usuario el nombre y la edad y muestre
#por consola la edad que tentra dentro de 10 años


#1) Escribe un programa que pida el nombre del usuario y muestre por consola
#un texto: “Hola nombreUsuario”
print("\n")
print("♦-----------------------------------------------------------------------------------------------♦")
print("\n")
print("#01)")
print("\n")
nombre_de_usuario=input("- ¿Cuál es tu nombre? :")
print("\n")
print("¡Hola",nombre_de_usuario,"!   ☻ ♥")
print("\n")
print("♦-----------------------------------------------------------------------------------------------♦")
#2) Escribe un programa que pida un número, luego pida otro número y
#muestre por consola el resultado de sumar dichos números.
print("\n")
print("#02)")
print("\n")
print("• Usar el \".\" para separar los decimales.")
print("\n")
a=float(input("- Por favor, ingrese cualquier número: "))
b=float(input("- Por favor, ingrese nuevamente cualquier número: "))
print("\n")
print("• La suma de los número es igual a: ",a+b)
print("\n")
print("♦-----------------------------------------------------------------------------------------------♦")
print("\n")
#3) Cree un programa que pida el nombre, el apellido, edad del usuario y luego
#muestre por consola los datos ingresados
print("#03)")
print("\n")
nombre=input("- Por favor ingrese su nombre: ")
apellido=input("- Por favor ingrese su apellido: ")
edad=int(input("- Por favor ingrese su edad: "))
print("\n")
print("• Sus datos son:")
print("\n")
print("- Nombre:",nombre)
print("- Apellido:",apellido)
print("- Edad:",edad)
print("\n")
print("♦-----------------------------------------------------------------------------------------------♦")
print("\n")
#4) Cree un programa que pida el nombre, número de comisión, asignatura,
#docente y si el usuario estuvo presente, luego que muestre los datos por
#consola con las leyendas pertinentes
print("\n")
print("#04)")
print("\n")
nombre2=input("- Por favor ingrese su nombre: ")
numero_de_comision=int(input("- Por favor ingrese su número de comisión: "))
asignatura=input("- Por favor ingrese su asignatura: ")
docente=input("- ¿Cuál es tu docente?: ")
asistencia=input("- ¿Estuvieste presete en la sistencia?: ")
print("\n")
print("• Sus datos son:")
print("\n")
print("- Nombre",nombre2)
print("- Número de comisió",numero_de_comision)
print("- Asignatura",asignatura)
print("- Dosente",docente)
print("- Asistencia",asistencia)
print("\n")
print("♦-----------------------------------------------------------------------------------------------♦")
print("\n")
#5) Cree un programa que pida el lado de un cuadrado y calcule la superficie
print("\n")
print("#05)")
print("\n")
lado_de_un_cuadrado=float(input("- Por favor, ingrese el lado de un cuadrado para calcular su superficie: "))
print("\n")
print("• La superficie de el cuadrado es igual a:")
print("\n")
print(lado_de_un_cuadrado*lado_de_un_cuadrado)
print("\n")
print("♦-----------------------------------------------------------------------------------------------♦")
print("\n")
#6) Cree un programa que pida los lados de un rectángulo y calcule la
#superficie
print("\n")
print("#06)")
print("\n")
h_de_un_rectngulo=float(input("- Por favor, ingrese la altura de el rectángulo para calcular su superficie: "))
b_de_un_rectngulo=float(input("- Por favor, ingrese la base de el rectángulo para calcular su superficie: "))
print("\n")
print("• La superficie de el rectángulo es igual a:")
print("\n")
print(h_de_un_rectngulo*b_de_un_rectngulo)
print("\n")
print("♦-----------------------------------------------------------------------------------------------♦")
print("\n")
#7) Cree un programa que calcule la superficie de un triángulo
print("\n")
print("#07)")
print("\n")
print("• El pregrama solo calcula la superficie de un triángulo equilátero.")
print("\n")
h_de_un_triangulo=float(input("- Por favor, ingrese la altura de el triángulo para calcular su superficie: "))
b_de_un_triangulo=float(input("- Por favor, ingrese la base de el triángulo para calcular su superficie: "))
print("\n")
print("• La fuperficie de el triágulo es igual a:")
print("\n")
print((h_de_un_triangulo*h_de_un_triangulo)/2)
print("\n")
print("♦-----------------------------------------------------------------------------------------------♦")
print("\n")
#8) Cree un programa que permite ingresar el nombre de un producto, el
#precio y que calcule el IVA.
print("\n")
print("#08)")
print("\n")
producto=input("- Por favor ingrese el nombre del producto: ")
precio=float(input("- Por favor ingrese el precio del producto: "))
print("\n")
print("• Produnto: ",producto)
print("\n")
print("• Precio: ",precio)
print("\n")
print("• Precio total más IVA")
print("\n")
iva=((precio/100)*21)
print(precio+iva)
print("\n")
print("♦-----------------------------------------------------------------------------------------------♦")
print("\n")
#9) cree un programa que calcule el promedio de un alumno, ingresando su
#nombre apellido, 3 notas, que muestre al final las leyendas pertinentes
print("\n")
print("#09)")
print("\n")
alumno=input("- Por favor ingrese su nombre: ")
apellido_alumno=input("- Por favor ingrese su apellido: ")
print("\n")
print("• Usar el \".\" para separar los decimales.")
print("\n")
matematicas=float(input("- Por favor, ingrese su nota de matemáticas: "))
literatura=float(input("- Por favor, ingrese su nota de literatura: "))
ingles=float(input("- Por favor, ingrese su nota de ingles: "))
print("\n")
print("• Alumno:")
print("\n")
print(alumno, apellido_alumno)
print("\n")
print("• Notas:")
print("\n")
print("- Matemáticas: ",matematicas)
print("- Literatura: ",literatura)
print("- Ingles: ",ingles)
print("\n")
print("• Promedio:")
print("\n")
print((matematicas+literatura+ingles)/3)
print("\n")
print("♦-----------------------------------------------------------------------------------------------♦")
print("\n")
#10) Cree un programa en el cual pida al usuario el nombre y la edad y muestre
#por consola la edad que tentra dentro de 10 años
print("\n")
print("#10)")
print("\n")
nombre3=input("- Por favor, ingrese su nombre: ")
edad2=int(input("- Por favor, ingrese su edad: "))
print("\n")
print("Querid@ ",nombre3," su edad dentro de 10 años es ",edad2+10," recerde comer bien, hacer ejercicio y descanzar para vivir más ☻.")
print("\n")
print("♦-----------------------------------------------------------------------------------------------♦")
